global_costmap:
  footprint: [[0.72, -0.47], [0.72, 0.47], [-0.72,0.47], [-0.72, -0.47]]
local_costmap:
  footprint: [[0.72, -0.47], [0.72, 0.47], [-0.72,0.47], [-0.72, -0.47]]
TebLocalPlannerROS:
  footprint_model:
    type: "polygon"
    vertices: [[0.72, -0.47], [0.72, 0.47], [-0.72,0.47], [-0.72, -0.47]]