global_costmap:
  footprint: [[0.55,-0.38],[0.55,0.38],[-0.55,0.38],[-0.55,-0.38]]
local_costmap:
  footprint: [[0.55,-0.38],[0.55,0.38],[-0.55,0.38],[-0.55,-0.38]]
TebLocalPlannerROS:
  footprint_model:
    type: "polygon"
    vertices: [[0.55,-0.38],[0.55,0.38],[-0.55,0.38],[-0.55,-0.38]]