global_costmap:
  footprint: [[0.58, -0.43], [0.58, 0.43], [-0.58,0.43], [-0.58, -0.43]]
local_costmap:
  footprint: [[0.58, -0.43], [0.58, 0.43], [-0.58,0.43], [-0.58, -0.43]]
TebLocalPlannerROS:
  footprint_model:
    type: "polygon"
    vertices: [[0.58, -0.43], [0.58, 0.43], [-0.58,0.43], [-0.58, -0.43]]
