<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find rbvogui_description)/urdf/wheels/wheel.gazebo.xacro" />
  <xacro:include filename="$(find rbvogui_description)/urdf/wheels/rubber_wheel_285mm.urdf.xacro" />

  <xacro:macro name="steering_wheel" params="prefix parent *origin reflect hq">
    <xacro:macro name="cylinder_inertia" params="m r h">
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}" />
    </xacro:macro>

    <xacro:property name="M_PI" value="3.1415926535897931" />

    <xacro:property name="steer_joint_damping" value="2.0" />
    <xacro:property name="steer_joint_friction" value="1.0" />
    <xacro:property name="steer_joint_effort_limit" value="2000.0" />
    <xacro:property name="steer_joint_velocity_limit" value="1000.0" />

    <!--MOTOR WHEEL -->
    <joint name="${prefix}steering_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${prefix}base_wheel"/>
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" rpy="0 0 0" />
      <limit effort="${steer_joint_effort_limit}" velocity="${steer_joint_velocity_limit}" lower="-3.00" upper="3.00"/>
      <dynamics damping="${steer_joint_damping}" friction="${steer_joint_friction}"/>
    </joint>

    <link name="${prefix}base_wheel">
      <visual>
        <!-- HIGH RESOLUTION WHEELS -->
        <xacro:if value="${hq}">
          <xacro:if value="${reflect}">
            <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
          </xacro:if>
          <xacro:unless value="${reflect}">
            <origin xyz="0 0 0.0" rpy="0 0 0" />
          </xacro:unless>
          <geometry>
            <mesh filename="package://rbvogui_description/meshes/wheels/hub_rbvogui_xl.stl" />
          </geometry> 
        </xacro:if>
         
        <!-- LOW RESOLUTION WHEELS -->
        <xacro:unless value="${hq}">
          <xacro:if value="${reflect}">
			      <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
          </xacro:if>
          <xacro:unless value="${reflect}">
            <origin xyz="0 0 0" rpy="0 0 0" />
          </xacro:unless>
          <geometry>
            <mesh filename="package://rbvogui_description/meshes/wheels/hub_rbvogui_xl.stl" />
          </geometry>
        </xacro:unless>
        <material name="red">
          <color rgba="0.9 0.1 0.1 1"/>     
        </material>
      </visual>

      <collision>
        <xacro:if value="${reflect}">
          <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
        </xacro:if>
        <xacro:unless value="${reflect}">
          <origin xyz="0 0 0.0" rpy="0 0 0" />
        </xacro:unless>
        <geometry>
          <mesh filename="package://rbvogui_description/meshes/wheels/hub_rbvogui_xl.stl" />
        </geometry>
      </collision>

      <inertial>
        <mass value="4" />
        <xacro:if value="${reflect}">
          <origin xyz="0 0 ${wheel_radius/1.5}" rpy="${M_PI/2.0} ${M_PI/2.0} 0"/>
        </xacro:if>
        <xacro:unless value="${reflect}">
          <origin xyz="0 0 ${wheel_radius/1.5}" rpy="${M_PI/2.0} ${M_PI/2.0} ${M_PI/2.0}"/>
        </xacro:unless>
        <xacro:cylinder_inertia m="5" r="0.1425" h="0.14"/>
      </inertial>
    </link>

    <xacro:gazebo_steering_frame_physics name="${prefix}base_wheel"/>
    <xacro:gazebo_steering_frame_material name="${prefix}base_wheel"/>

    <xacro:wheel_285mm prefix="${prefix}" parent="${prefix}base_wheel" reflect="${reflect}" hq="${hq}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:wheel_285mm>
  </xacro:macro>
</robot>
