<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find rbvogui_description)/urdf/wheels/wheel.gazebo.xacro" />
  <xacro:include filename="$(find rbvogui_description)/urdf/wheels/rubber_wheel.urdf.xacro" />

  <xacro:property name="wheel_radius" value="0.1175" /> <!-- teorically D: 0.235-->

  <xacro:macro name="steering_wheel" params="prefix parent *origin reflect hq">
    <xacro:macro name="cylinder_inertia" params="m r h">
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}" />
    </xacro:macro>

    <xacro:property name="steering_support_mass" value="2.5" />
    <xacro:property name="steering_support_width" value="0.1"/>

    <xacro:property name="steer_joint_damping" value="1.0" />
    <xacro:property name="steer_joint_friction" value="1.0" />
    <xacro:property name="steer_joint_effort_limit" value="200.0" />
    <xacro:property name="steer_joint_velocity_limit" value="100.0" />

    <!-- TODO: check reflect parameter -->
    <!--MOTOR WHEEL -->
    <joint name="${prefix}steering_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${prefix}base_wheel"/>
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" rpy="0 0 0" />
      <!-- limit effort="${steer_joint_effort_limit}" velocity="${steer_joint_velocity_limit}" lower="-1.5708" upper="1.5708" / -->
      <limit effort="${steer_joint_effort_limit}" velocity="${steer_joint_velocity_limit}" lower="-3.00" upper="3.00"/>
      <dynamics damping="${steer_joint_damping}" friction="${steer_joint_friction}"/>
    </joint>

    <link name="${prefix}base_wheel">
      <visual>
        <!-- HIGH RESOLUTION WHEEL -->
        <xacro:if value="${hq}">
          <xacro:if value="${reflect}">
            <origin xyz="0 0 0.0" rpy="0 0 0" />
          </xacro:if>
          <xacro:unless value="${reflect}">
            <origin xyz="0 0 0.0" rpy="0 0 ${M_PI}" />
          </xacro:unless>
          <geometry>
            <mesh filename="package://rbvogui_description/meshes/wheels/mw_frame_stl_color.dae" />
          </geometry>
        </xacro:if>

          <!-- LOW RESOLUTION WHEEL -->
        <xacro:unless value="${hq}">
          <xacro:if value="${reflect}">
            <origin xyz="0 0 0.0" rpy="0 0 0" />
          </xacro:if>
          <xacro:unless value="${reflect}">
            <origin xyz="0 0 0.0" rpy="0 0 ${M_PI}" />
          </xacro:unless>
          <geometry>
            <mesh filename="package://rbvogui_description/meshes/wheels/mw_frame_stl_color.dae" />
          </geometry>
        </xacro:unless>

        <material name="red">
          <color rgba="0.9 0.1 0.1 1"/>     
        </material>
      </visual>

      <collision>
        <xacro:if value="${reflect}">
          <origin xyz="0 0 0.0" rpy="0 0 0" />
        </xacro:if>
        <xacro:unless value="${reflect}">
          <origin xyz="0 0 0.0" rpy="0 0 ${M_PI}" />
        </xacro:unless>
        <geometry>
          <mesh filename="package://rbvogui_description/meshes/wheels/mw_frame_stl_color.dae" />
        </geometry>        
      </collision>

      <inertial>
        <mass value="${steering_support_mass}" />
        <xacro:if value="${reflect}">
          <origin xyz="0 0 ${wheel_radius/1.5}" rpy="${M_PI/2.0} ${M_PI/2.0} 0"/>
        </xacro:if>
        <xacro:unless value="${reflect}">
          <origin xyz="0 0 ${wheel_radius/1.5}" rpy="${M_PI/2.0} ${M_PI/2.0} ${M_PI/2.0}"/>
        </xacro:unless>
        <xacro:cylinder_inertia m="${steering_support_mass}" r="${wheel_radius}" h="${steering_support_width}" />
      </inertial>
    </link>

    <xacro:gazebo_steering_frame_physics name="${prefix}base_wheel"/>
    <!--xacro:gazebo_steering_frame_material name="${prefix}base_wheel"/-->

    <xacro:wheel prefix="${prefix}" parent="${prefix}base_wheel" reflect="${reflect}" hq="${hq}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:wheel>
  </xacro:macro>
</robot>
