<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Height added: 0.1125 m -->
  <xacro:macro name="wheel" params="prefix parent *origin reflect:=false hq:=true">
    <xacro:macro name="cylinder_inertia" params="m r h">
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" 
               iyy="${m*(3*r*r+h*h)/12}" iyz="0" 
               izz="${m*r*r/2}" />
    </xacro:macro>

    <xacro:property name="M_PI"        value="3.1415926535897931"/>
    <xacro:property name="tire_radius" value="0.1125"/>
    <xacro:property name="tire_width"  value="0.1275"/>
    <xacro:property name="tire_mass"   value="5.0"/>

    <joint name="${prefix}wheel_joint" type="continuous">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}wheel_link"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.1" friction="0.1"/>
      <limit effort="1e9" velocity="1000.0"/>
      <safety_controller k_velocity="0.1" k_position="0.1" soft_lower_limit="-${M_PI}" soft_upper_limit="${M_PI}"/>
    </joint>

    <link name="${prefix}wheel_link">
      <inertial>
        <xacro:if value="${reflect}">
          <origin xyz="0 0 ${tire_width/2}" rpy="${M_PI/2} 0 0" />
        </xacro:if>
        <xacro:unless value="${reflect}">
          <origin xyz="0 0 -${tire_width/2}" rpy="${M_PI/2} 0 0" />
        </xacro:unless>
        <mass value="${tire_mass}"/>
        <xacro:cylinder_inertia m="${tire_mass}" r="${tire_radius}" h="${tire_width}"/>
      </inertial>

      <visual>
        <xacro:if value="${reflect}">
          <origin xyz="0 0 ${tire_width/2}" rpy="${M_PI/2} 0 0" />
        </xacro:if>
        <xacro:unless value="${reflect}">
          <origin xyz="0 0 -${tire_width/2}" rpy="${M_PI/2} 0 0" />
        </xacro:unless>
        <geometry>
          <xacro:if value="${hq}">
            <mesh filename="package://rbvogui_description/meshes/wheels/wheel_sxl.stl" />
          </xacro:if>
          <xacro:unless value="${hq}">
            <cylinder length="${tire_width}" radius="${tire_radius}" />
          </xacro:unless>
        </geometry>
        <material name="dark-gray">
          <color rgba="0.17 0.17 0.17 1.0"/>
        </material>
      </visual>

      <collision>
        <xacro:if value="${reflect}">
          <origin xyz="0 0 ${tire_width/2}" rpy="0 0 0" />
        </xacro:if>
        <xacro:unless value="${reflect}">
          <origin xyz="0 0 -${tire_width/2}" rpy="0 0 0" />
        </xacro:unless>
        <geometry>
          <cylinder length="${tire_width}" radius="${tire_radius}" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="${prefix}wheel_link">  
      <material>Gazebo/DarkGrey</material>
      <mu1>0.90</mu1>
      <mu2>0.85</mu2>
      <kp>4.75e5</kp>
      <kd>8.25e2</kd>
    </gazebo>
  </xacro:macro>
</robot>