<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cart_connection">

  <xacro:arg name="prefix" default="robot_" />
  <xacro:arg name="connected" default="true" />

  <!-- Transform from robot_base_link to bulon -->
  <xacro:property name="bulon_x" value="-0.669" />
  <xacro:property name="bulon_z" value="0.391" />

  <!-- Transform from hitch to chassis UNKOWN -->
  <xacro:property name="hitch_x" value="-0.620" />
  <xacro:property name="hitch_z" value="0.161" />

  <!-- Hitch -->
  <xacro:property name="hitch_length" value="0.215" />
  <xacro:property name="hitch_width" value="0.160" />
  <xacro:property name="hitch_height" value="0.064" />

  <xacro:macro name="cart_connection" params="prefix connected">

    <!-- Robot to bulon NOMBRE PROVISIONAL SUPONGO??-->
            <link name="${prefix}bulon">
                <inertial>
                    <mass value="1" />
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <xacro:solid_cuboid_inertia w="${0.01}" d="${0.01}" h="${0.01}" m="10"/>
                </inertial>
                <visual>
                <origin xyz="0.0 0.0 -0.0975" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="0.015" length="0.195"/>
                </geometry>
                </visual>
                <collision>
                <origin xyz="0.0 0.0 -0.0975" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="0.015" length="0.195"/>
                </geometry>
                </collision>
            </link>

            <joint name="${prefix}bulon_joint" type="fixed">
                <origin xyz="${bulon_x} 0 ${bulon_z}" rpy="0.0 0.0 0.0"/>
                <parent link="robot_base_link"/>
                <child link="${prefix}bulon"/>
            </joint>

            <!-- bulon to Hitch -->
            <link name="${prefix}hitch_z">
            <inertial>
                    <mass value="3" />
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <xacro:solid_cuboid_inertia w="0.215" d="0.064" h="0.160" m="3"/>
            </inertial>
            </link>

            <xacro:if value="${connected}">
              <joint name="${prefix}hitch_z_joint" type="revolute">
                  <origin xyz="${hitch_x - bulon_x} 0 ${hitch_z-bulon_z}" rpy="0.0 0.0 0.0"/>
                  <parent link="${prefix}bulon"/>
                  <child link="${prefix}hitch_z"/>
                  <axis xyz="0.0 0.0 1.0"/>
                  <limit effort="1000" velocity="2000" lower="${-PI/9}" upper="${PI/9}"/>
              </joint>
            </xacro:if>
            <xacro:unless value="${connected}">
              <joint name="${prefix}hitch_z_joint" type="fixed">
                  <origin xyz="${hitch_x - bulon_x} 0 ${hitch_z-bulon_z}" rpy="0.0 0.0 0.0"/>
                  <parent link="${prefix}bulon"/>
                  <child link="${prefix}hitch_z"/>
              </joint>
            </xacro:unless>

            <link name="${prefix}hitch_y">
            <inertial>
                    <mass value="3" />
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <xacro:solid_cuboid_inertia w="0.215" d="0.064" h="0.160" m="3"/>
            </inertial>
            </link>

            <xacro:if value="${connected}">
              <joint name="${prefix}hitch_y_joint" type="revolute">
                  <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                  <parent link="${prefix}hitch_z"/>
                  <child link="${prefix}hitch_y"/>
                  <axis xyz="0.0 1.0 0.0"/>
                  <limit effort="1000" velocity="2000" lower="${-PI/9}" upper="${PI/9}"/>
              </joint>
            </xacro:if>
            <xacro:unless value="${connected}">
              <joint name="${prefix}hitch_y_joint" type="fixed">
                  <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                  <parent link="${prefix}hitch_z"/>
                  <child link="${prefix}hitch_y"/>
              </joint>
            </xacro:unless>

            <link name="${prefix}hitch_x">
            <inertial>
                    <mass value="3" />
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <xacro:solid_cuboid_inertia w="0.215" d="0.064" h="0.160" m="3"/>
            </inertial>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                <box size="0.215 0.160 0.064"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                <box size="${hitch_length} ${hitch_width} ${hitch_height}"/>
                </geometry>
            </collision>
            </link>

            <xacro:if value="${connected}">
              <joint name="${prefix}hitch_x_joint" type="revolute">
                  <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                  <parent link="${prefix}hitch_y"/>
                  <child link="${prefix}hitch_x"/>
                  <axis xyz="1.0 0.0 0.0"/>
                  <limit effort="1000" velocity="2000" lower="${-PI/7}" upper="${PI/7}"/>
              </joint>
            </xacro:if>
            <xacro:unless value="${connected}">
              <joint name="${prefix}hitch_x_joint" type="fixed">
                  <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                  <parent link="${prefix}hitch_y"/>
                  <child link="${prefix}hitch_x"/>
              </joint>
            </xacro:unless>

  </xacro:macro>

</robot>