<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_name">
    <xacro:macro name="cart_joints" params="prefix parent">

    <!-- Robot to BULON -->
        <joint name="${prefix}bulon_joint" type="fixed">
            <origin xyz="${bulon_x} 0 ${bulon_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${parent}"/>
            <child link="${prefix}bulon"/>
        </joint>

    <!-- BULON to Hitch -->
        <joint name="${prefix}hitch_z_joint" type="revolute">
            <origin xyz="${hitch_x} 0 ${hitch_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${parent}"/>
            <child link="${prefix}hitch_z"/>
            <axis xyz="0.0 0.0 1.0"/>
            <limit effort="1000" velocity="2000" lower="${-PI/6}" upper="${PI/6}"/>
        </joint>

        <joint name="${prefix}hitch_y_joint" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}hitch_z"/>
            <child link="${prefix}hitch_y"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000" lower="${-PI/6}" upper="${PI/6}"/>
        </joint>

        <joint name="${prefix}hitch_x_joint" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}hitch_y"/>
            <child link="${prefix}hitch_x"/>
            <axis xyz="1.0 0.0 0.0"/>
            <limit effort="1000" velocity="2000" lower="${-PI/6}" upper="${PI/6}"/>
        </joint>

    <!-- Hitch to Body -->
        <joint name="${prefix}body_joint" type="revolute">
            <origin xyz="${-cart_length/2 -hitch_length/2} 0 0" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}hitch_x"/>
            <child link="${prefix}body"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000" lower="-0.2" upper="0.2"/>
        </joint>

    <!-- Rear Left wheel -->
        <joint name="${prefix}rear_left_wheel_joint" type="continuous">
            <origin xyz="${rear_wheel_x} ${rear_wheel_y} ${rear_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}body"/>
            <child link="${prefix}rear_left_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    <!-- Rear Right wheel -->
        <joint name="${prefix}rear_right_wheel_joint" type="continuous">
            <origin xyz="${rear_wheel_x} -${rear_wheel_y} ${rear_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}body"/>
            <child link="${prefix}rear_right_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
            
        </joint>

    <!-- Front Right Wheel support base-->
        <joint name="${prefix}front_right_wheel_base_support_joint" type="fixed">
            <origin xyz="${front_caster_wheel_x} ${-front_caster_wheel_y} ${front_caster_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}body"/>
            <child link="${prefix}front_right_wheel_base_support"/>
        </joint>

    <!-- Front Left Wheel support base-->
        <joint name="${prefix}front_left_wheel_base_support_joint" type="fixed">
            <origin xyz="${front_caster_wheel_x} ${front_caster_wheel_y} ${front_caster_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}body"/>
            <child link="${prefix}front_left_wheel_base_support"/>
        </joint>

    <!-- Front Right Wheel support -->
        <joint name="${prefix}front_right_wheel_support_joint" type="continuous">
            <origin xyz="${front_caster_wheel_x} ${-front_caster_wheel_y} ${front_caster_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}body"/>
            <child link="${prefix}front_right_wheel_support"/>
            <axis xyz="0.0 0.0 1.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    <!-- Front Left Wheel support -->
        <joint name="${prefix}front_left_wheel_support_joint" type="continuous">
            <origin xyz="${front_caster_wheel_x} ${front_caster_wheel_y} ${front_caster_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}body"/>
            <child link="${prefix}front_left_wheel_support"/>
            <axis xyz="0.0 0.0 1.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    <!-- Front Left wheel -->
        <joint name="${prefix}front_left_wheel_joint" type="continuous">
            <origin xyz="${front_wheel_x} 0 ${front_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}front_left_wheel_support"/>
            <child link="${prefix}front_left_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    <!-- Front Right wheel -->
        <joint name="${prefix}front_right_wheel_joint" type="continuous">
            <origin xyz="${front_wheel_x} 0 ${front_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}front_right_wheel_support"/>
            <child link="${prefix}front_right_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    </xacro:macro>
</robot>
