<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_name">
    <xacro:macro name="cart_joints" params="prefix parent">

    <!-- Robot to Hitch -->
        <joint name="${prefix}hitch_z_joint" type="revolute">
            <origin xyz="-0.5 0 ${wheels_radius + cart_height/2}" rpy="0.0 0.0 0.0"/>
            <parent link="${parent}"/>
            <child link="${prefix}hitch_z"/>
            <axis xyz="0.0 0.0 1.0"/>
            <limit effort="1000" velocity="2000" lower="${-PI/6}" upper="${PI/6}"/>
        </joint>

        <joint name="${prefix}hitch_y_joint" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}hitch_z"/>
            <child link="${prefix}hitch_y"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000" lower="${-PI/6}" upper="${PI/6}"/>
        </joint>

        <joint name="${prefix}hitch_x_joint" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}hitch_y"/>
            <child link="${prefix}hitch_x"/>
            <axis xyz="1.0 0.0 0.0"/>
            <limit effort="1000" velocity="2000" lower="${-PI/6}" upper="${PI/6}"/>
        </joint>

    <!-- Hitch to Body -->
        <joint name="${prefix}body_joint" type="fixed">
            <origin xyz="${-cart_length/2 -hitch_length} 0 0" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}hitch_x"/>
            <child link="${prefix}body"/>
        </joint>

    <!-- Left wheel -->
        <joint name="${prefix}left_wheel_joint" type="continuous">
            <origin xyz="${-wheels_center_dist_x} ${cart_width / 2 + wheels_width / 2} ${-cart_height/2}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}body"/>
            <child link="${prefix}left_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    <!-- Right wheel -->
        <joint name="${prefix}right_wheel_joint" type="continuous">
            <origin xyz="${-wheels_center_dist_x} ${-cart_width / 2 - wheels_width / 2} ${-cart_height/2}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}body"/>
            <child link="${prefix}right_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    <!-- Front Right Wheel support -->
        <joint name="${prefix}support_front_right_wheel_joint" type="continuous">
            <origin xyz="${front_wheel_center_dist_x} ${-front_wheel_center_dist_y} ${-cart_height/2-support_length/2}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}body"/>
            <child link="${prefix}support_front_right_wheel"/>
            <axis xyz="0.0 0.0 1.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    <!-- Front Left Wheel support -->
        <joint name="${prefix}support_front_left_wheel_joint" type="continuous">
            <origin xyz="${front_wheel_center_dist_x} ${front_wheel_center_dist_y} ${-cart_height/2-support_length/2}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}body"/>
            <child link="${prefix}support_front_left_wheel"/>
            <axis xyz="0.0 0.0 1.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    <!-- Front Left wheel -->
        <joint name="${prefix}front_left_wheel_joint" type="continuous">
            <origin xyz="-0.05 0 ${-support_length/2}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}support_front_left_wheel"/>
            <child link="${prefix}front_left_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    <!-- Front Right wheel -->
        <joint name="${prefix}front_right_wheel_joint" type="continuous">
            <origin xyz="-0.05 0 ${-support_length/2}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}support_front_right_wheel"/>
            <child link="${prefix}front_right_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
        </joint>

    </xacro:macro>
</robot>
