<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_name">

    <xacro:arg name="prefix" default="robot_cart_" />
    <xacro:arg name="connected" default="true" />

    <xacro:macro name="cart_joints" params="prefix connected">

    <!-- Hitch to chassis -->

        <xacro:if value="${connected}">
            <joint name="${prefix}chassis_joint" type="revolute">
                <origin xyz="${-cart_length/2 - 0.2} 0 0" rpy="0.0 0.0 0.0"/>
                <parent link="robot_hitch_x"/>
                <child link="${prefix}chassis"/>
                <axis xyz="0.0 1.0 0.0"/>
                <limit effort="1000" velocity="2000" lower="-0.2" upper="0.2"/>
            </joint>
        </xacro:if>

        <xacro:unless value="${connected}">
            <joint name="${prefix}chassis_joint" type="fixed">
                <origin xyz="0 0 0.3" rpy="0.0 0.0 0.0"/>
                <parent link="${prefix}base_footprint"/>
                <child link="${prefix}chassis"/>
            </joint>
        </xacro:unless>

    <!-- Rear Left wheel -->
        <joint name="${prefix}rear_left_wheel_joint" type="continuous">
            <origin xyz="${rear_wheel_x} ${rear_wheel_y} ${rear_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}chassis"/>
            <child link="${prefix}rear_left_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
            <dynamics damping="0.8" friction="2.0"/>
            
        </joint>

    <!-- Rear Right wheel -->
        <joint name="${prefix}rear_right_wheel_joint" type="continuous">
            <origin xyz="${rear_wheel_x} -${rear_wheel_y} ${rear_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}chassis"/>
            <child link="${prefix}rear_right_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
            <dynamics damping="0.8" friction="2.0"/>
            
        </joint>

    <!-- Front Right Wheel support base-->
        <joint name="${prefix}front_right_wheel_base_support_joint" type="fixed">
            <origin xyz="${front_caster_wheel_x} ${-front_caster_wheel_y} ${front_caster_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}chassis"/>
            <child link="${prefix}front_right_wheel_base_support"/>
        </joint>

    <!-- Front Left Wheel support base-->
        <joint name="${prefix}front_left_wheel_base_support_joint" type="fixed">
            <origin xyz="${front_caster_wheel_x} ${front_caster_wheel_y} ${front_caster_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}chassis"/>
            <child link="${prefix}front_left_wheel_base_support"/>
        </joint>

    <!-- Front Right Wheel support -->
        <joint name="${prefix}front_right_wheel_support_joint" type="continuous">
            <origin xyz="${front_caster_wheel_x} ${-front_caster_wheel_y} ${front_caster_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}chassis"/>
            <child link="${prefix}front_right_wheel_support"/>
            <axis xyz="0.0 0.0 1.0"/>
            <limit effort="1000" velocity="2000"/>
            <dynamics damping="0.8" friction="2.0"/>
        </joint>

    <!-- Front Left Wheel support -->
        <joint name="${prefix}front_left_wheel_support_joint" type="continuous">
            <origin xyz="${front_caster_wheel_x} ${front_caster_wheel_y} ${front_caster_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}chassis"/>
            <child link="${prefix}front_left_wheel_support"/>
            <axis xyz="0.0 0.0 1.0"/>
            <limit effort="1000" velocity="2000"/>
            <dynamics damping="0.8" friction="2.0"/>
        </joint>

    <!-- Front Left wheel -->
        <joint name="${prefix}front_left_wheel_joint" type="continuous">
            <origin xyz="${front_wheel_x} 0 ${front_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}front_left_wheel_support"/>
            <child link="${prefix}front_left_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
            <dynamics damping="0.8" friction="2.0"/>
        </joint>

    <!-- Front Right wheel -->
        <joint name="${prefix}front_right_wheel_joint" type="continuous">
            <origin xyz="${front_wheel_x} 0 ${front_wheel_z}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}front_right_wheel_support"/>
            <child link="${prefix}front_right_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <limit effort="1000" velocity="2000"/>
            <dynamics damping="0.8" friction="2.0"/>
        </joint>

    <!-- Marker00 -->
        <joint name="${prefix}marker00_joint" type="fixed">
            <origin xyz="0.67 -0.3 0.05" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}chassis"/>
            <child link="${prefix}marker00"/>
        </joint>

    <!-- Marker01 -->
        <joint name="${prefix}marker01_joint" type="fixed">
            <origin xyz="0.67 0.3 0.05" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}chassis"/>
            <child link="${prefix}marker01"/>
        </joint>

    <!-- Marker10 -->
        <joint name="${prefix}marker10_joint" type="fixed">
            <origin xyz="0.67 -0.10 0.05" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}chassis"/>
            <child link="${prefix}marker10"/>
        </joint>

    <!-- Marker11 -->
        <joint name="${prefix}marker11_joint" type="fixed">
            <origin xyz="0.67 0.10 0.05" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}chassis"/>
            <child link="${prefix}marker11"/>
        </joint>

    </xacro:macro>
</robot>
