controller_manager:
  ros__parameters:
    update_rate: 25  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

diffbot_base_controller:
  ros__parameters:
    left_wheel_names: ["robot_front_left_wheel_joint"]
    right_wheel_names: ["robot_front_right_wheel_joint"]

    wheel_separation: 0.60
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.1

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: -1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: robot_odom22
    base_frame_id: robot_base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

joint_trajectory_controller:
  ros__parameters:
    joints:
#      - robot_rear_left_wheel_joint
#      - robot_rear_right_wheel_joint
#      - robot_front_left_wheel_joint
#      - robot_front_right_wheel_joint
      - robot_rear_right_base_set_joint # robot_front_left_steering_joint
      - robot_rear_left_base_set_joint # robot_front_right_steering_joint
      - robot_front_right_base_set_joint # robot_rear_left_steering_joint
      - robot_front_left_base_set_joint # robot_rear_right_steering_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
    interface_name: position