<?xml version="1.0"?>
<robot name="rbvogui" xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:include filename="$(find rbvogui_description)/urdf/wheels/wheel_set.urdf.xacro"/>
  <xacro:include filename="$(find rbvogui_description)/urdf/bases/default.urdf.xacro"/>

  <xacro:property name="M_PI" value="3.1415926535897931" />
  
  <xacro:macro name="rbvogui" params="prefix publish_bf hq">
    <xacro:property name="wheel_offset_x" value="0.380"/>
    <xacro:property name="wheel_offset_y" value="0.23975"/>
    <xacro:property name="wheel_offset_z" value="-0.012"/>

    <xacro:property name="wheel_radius" value="0.1175"/>
    <xacro:property name="wheel_width"  value="0.1175"/>
    <xacro:property name="wheel_mass"   value="5.0000"/>

    <xacro:if value="${publish_bf}">
      <link name="${prefix}base_footprint">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.001 0.001 0.001" />
          </geometry>
        </visual>
      </link>

      <joint name="${prefix}base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius+0.138}" rpy="0 0 0" />
        <parent link="${prefix}base_footprint"/>
        <child link="${prefix}base_link" />
      </joint>
    </xacro:if>

    <xacro:rbvogui_base prefix="${prefix}" hq="${hq}"/>

    <xacro:wheel_set prefix="${prefix}front_left_" parent="${prefix}base_link" reflect="true" hq="true">
      <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 ${M_PI} 0"/>
    </xacro:wheel_set>

    <xacro:wheel_set prefix="${prefix}front_right_" parent="${prefix}base_link" reflect="false" hq="true">
      <origin xyz="${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="0 ${M_PI} ${M_PI}"/>
    </xacro:wheel_set>

    <xacro:wheel_set prefix="${prefix}rear_left_" parent="${prefix}base_link" reflect="true" hq="true">
      <origin xyz="-${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 ${M_PI} 0"/>
    </xacro:wheel_set>

    <xacro:wheel_set prefix="${prefix}rear_right_" parent="${prefix}base_link" reflect="false" hq="true">
      <origin xyz="-${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="0 ${M_PI} ${M_PI}"/>
    </xacro:wheel_set>

    <xacro:macro name="ros2_joint" params="interface jmin jmax prefix name">
      <joint name="${prefix}${name}_joint">
        <command_interface name="${interface}">
          <param name="min">${jmin}</param>
          <param name="max">${jmax}</param>
        </command_interface>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
        <state_interface name="effort"/>
      </joint>
    </xacro:macro>
    <ros2_control name="GazeboSystem" type="system">
      <hardware>
        <plugin>gazebo_ros2_control/GazeboSystem</plugin>
      </hardware>

      <xacro:ros2_joint interface="position" jmin="-2" jmax="2" prefix="${prefix}" name="front_left_base_set"/>
      <xacro:ros2_joint interface="position" jmin="-2" jmax="2" prefix="${prefix}" name="front_right_base_set"/>
      <xacro:ros2_joint interface="position" jmin="-2" jmax="2" prefix="${prefix}" name="rear_left_base_set"/>
      <xacro:ros2_joint interface="position" jmin="-2" jmax="2" prefix="${prefix}" name="rear_right_base_set"/>

      <xacro:ros2_joint interface="velocity" jmin="-10" jmax="10" prefix="${prefix}" name="front_left_wheel"/>
      <xacro:ros2_joint interface="velocity" jmin="-10" jmax="10" prefix="${prefix}" name="front_right_wheel"/>
      <xacro:ros2_joint interface="velocity" jmin="-20" jmax="20" prefix="${prefix}" name="rear_left_wheel"/>
      <xacro:ros2_joint interface="velocity" jmin="-20" jmax="20" prefix="${prefix}" name="rear_right_wheel"/>
    </ros2_control>

  </xacro:macro>

  <xacro:arg name="robot_id"             default="robot" />
  <xacro:arg name="prefix"               default="$(arg robot_id)_" />
  <xacro:arg name="config_controllers"   default="/home/rafaelm/git/robotnikautomation/FRAUNHOFER_RBVOGUI/rbvogui_sim/rbvogui_gazebo/config/controllers2.yaml" />

  <xacro:property name="hq" value="true" />
  <xacro:property name="publish_bf" value="true" />

  <xacro:rbvogui prefix="$(arg prefix)" publish_bf="${publish_bf}" hq="${hq}" />
  
  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="robotnik2_gazebo_control">
      <namespace>$(arg robot_id)</namespace>
      <parameters>$(arg config_controllers)</parameters>
      <!--robot_param>robot_description</robot_param-->
      <!--robot_param_node>robot_state_publisher</robot_param_node-->
      <!--remaping>$(find rbvogui_description)/config/remapping.yaml</remaping-->
    </plugin>
  </gazebo>

</robot>
