docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 100.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.05
    max_retries: 3
    base_frame: "robot_base_link"
    fixed_frame: "robot_odom"
    dock_backwards: false
    dock_prestaging_tolerance: 0.5

    # Types of docks
    dock_plugins: ['front_dock', 'rear_dock']
    front_dock:
      # plugin: 'nova_carter_dock::NovaCarterChargingDock'
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.01
      staging_x_offset: 1.0
      use_external_detection_pose: true
      use_battery_status: false # true
      use_stall_detection: false

      external_detection_timeout: 20.0
      external_detection_translation_x: -1.5
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: 1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    rear_dock:
      # plugin: 'nova_carter_dock::NovaCarterChargingDock'
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.01
      staging_x_offset: -0.9
      use_external_detection_pose: true
      use_battery_status: false # true
      use_stall_detection: false

      external_detection_timeout: 20.0
      external_detection_translation_x: 1.0
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57 #1.57
      external_detection_rotation_pitch: 1.57 #-1.57
      external_detection_rotation_yaw: -3.141592
      filter_coef: 0.1

    # Dock instances
    docks: ['home_dock', 'back_dock']
    home_dock:
      type: 'front_dock'
      frame: robot_map
      pose: [-2.442, 0.0, 0.0]
    back_dock:
      type: 'rear_dock'
      frame: robot_map
      pose: [-2.442, 0.0, 0.0]

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15